import logging

from fastapi import APIRouter, HTTPException

from app.models.schemas import QueryRequest, QueryResponse, SourceChunk
from app.services.embedder import embed_query
from app.services.llm import generate_answer
from app.services.vectorstore import search

logger = logging.getLogger(__name__)

router = APIRouter(tags=["query"])


@router.post("/query")
async def query(request: QueryRequest):
    """
    This function processes a user query and returns an
    answer generated by AI using the most relevant chunks
    retrieved from chromaDB (up to request.top_k_chunks)


    Args:
        request (QueryRequest): The incomming request that
                                contains the user query.

    Returns:
        QueryResponse: AI-generaterd answer using the source chunks
                        and the sources
    """
    try:

        query_vector = embed_query(request.query)

        raw_results = search(query_vector, top_k=request.top_k_chunks)

        sources = []
        for doc, meta, distance in zip(
            raw_results["documents"][0],
            raw_results["metadatas"][0],
            raw_results["distances"][0],
        ):
            sources.append(
                SourceChunk(
                    text=doc,
                    file_name=meta["filename"],
                    chunk_index=meta["chunk_index"],
                    similarity_score=round(1 - distance / 2, 4),
                )
            )

        answer, used_sources = generate_answer(request.query, sources)

        # Keep only the chunks the answer actually relied on, preserving
        # their similarity-ranked order (used_sources are 1-based, see #12).
        used = {n for n in used_sources if 1 <= n <= len(sources)}
        cited_sources = [src for i, src in enumerate(sources, start=1) if i in used]

        return QueryResponse(
            query=request.query, response=answer, sources=cited_sources
        )
    except Exception:
        logger.exception("Error processing query")
        raise HTTPException(
            status_code=500, detail="Internal error processing the query."
        )
