from fastapi import APIRouter, HTTPException

from app.models.schemas import QueryRequest, QueryResponse, SourceChunk
from app.services.embedder import embed_query
from app.services.llm import generate_answer
from app.services.vectorstore import search

router = APIRouter(tags=["query"])


@router.post("/query")
async def query(request: QueryRequest):
    """
    This function processes a user query and returns an
    answer generated by AI using the top 5 chunks retrived
    from chromaDB


    Args:
        request (QueryRequest): The incomming request that
                                contains the user query.

    Returns:
        QueryResponse: AI-generaterd answer using the source chunks
                        and the sources
    """
    try:

        query_vector = embed_query(request.query)

        raw_results = search(query_vector)

        sources = []
        for doc, meta, distance in zip(
            raw_results["documents"][0],
            raw_results["metadatas"][0],
            raw_results["distances"][0],
        ):
            sources.append(
                SourceChunk(
                    text=doc,
                    file_name=meta["filename"],
                    chunk_index=meta["chunk_index"],
                    similarity_score=round(1 - distance / 2, 4),
                )
            )

        answer = generate_answer(request.query, sources)

        return QueryResponse(query=request.query, response=answer, sources=sources)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
