from fastapi import APIRouter

from app.models.schemas import QueryRequest, QueryResponse
from app.services.embedder import embed_query
from app.services.llm import generate_answer
from app.services.vectorstore import search

router = APIRouter(tags=["query"])


@router.post("/query")
async def query(request: QueryRequest):
    """
    This function processes a user query and returns an
    answer generated by AI using the top 5 chunks retrived
    from chromaDB


    Args:
        request (QueryRequest): The incomming request that
                                contains the user query.

    Returns:
        QueryResponse: AI-generaterd answer using the source chunks
                        and the sources
    """
    query_vector = embed_query(request.query)

    chunks = search(query_vector)

    answer = generate_answer(request.query, chunks)

    return QueryResponse(answer=answer, sources=chunks)
