from typing import Optional

from pydantic import BaseModel, Field

# INGESTION


class IngestResponse(BaseModel):
    """
    Response returned after a document is successfully
    ingested into ChromaDB.

    Args:
        filename (str): Name of the uploaded document.
        chunks_created (int): Number of text chunks generated
            from the document.
        message (str): Status message describing the ingestion result.
    """

    filename: str
    chunks_created: int
    message: str


class DeleteResponse(BaseModel):
    """
    Response returned after a document is deleted from
    the vector database.

    Args:
        filename (str): Name of the deleted document.
        chunks_deleted (int): Number of chunks removed
            from the database.
        message (str): Status message describing the deletion result.
    """

    filename: str
    chunks_deleted: int
    message: str


# QUERYING


class QueryRequest(BaseModel):
    """
    Request body used when submitting a query to the API.

    Args:
        query (str): User's question or search query.
        top_k_chunks (Optional[int]): Number of most relevant
            chunks to retrieve from the vector database.
            Must be between 1 and 20.
    """

    query: str = Field(..., min_length=1, max_length=2000)
    top_k_chunks: Optional[int] = Field(
        default=5, ge=1, le=20
    )  # greater than or equal to 1 and less than or equal to 20


class SourceChunk(BaseModel):
    """
    Represents a text chunk retrieved from the vector database
    as part of a similarity search.

    Args:
        text (str): Retrieved text chunk content.
        file_name (str): Name of the source document.
        chunk_index (int): Position of the chunk within
            the original document.
        similarity_score (float): Cosine similarity score
            between the query embedding and chunk embedding.
    """

    text: str  # The text chunk that retrived from Chroma DB
    file_name: str  # Nmae of the file the text is retrived from
    chunk_index: int  # Index of the chunk
    similarity_score: float  # Cosine similariy score


class QueryResponse(BaseModel):
    """
    Response returned after generating an answer using the LLM.

    Args:
        query (str): Original user query.
        response (str): Answer generated by the LLM.
        sources (list[SourceChunk]): Source chunks used
            to generate the response.
    """

    query: str  # The original query
    response: str  # The response LLM generated
    sources: list[SourceChunk]  # The souce chunks LLM used to generate the answer


class DbInfo(BaseModel):
    """
    Information about the current state of the vector database.

    Args:
        total_chunks (int): Total number of stored chunks.
        documents (list[str]): List of document names currently
            stored in the database.
    """

    total_chunks: int
    documents: list[str]
